const STATUS_BADGE_COLOR = {
  Created: "bg-gray-100 text-gray-700",
  Assigned: "bg-blue-100 text-blue-700",
  PickedUp: "bg-purple-100 text-purple-700",
  AtOffice: "bg-indigo-100 text-indigo-700",
  Dispatched: "bg-green-100 text-green-700",
  Cancelled: "bg-red-100 text-red-700",
};

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const formatScheduled = (isoString) => {
  if (!isoString) return "—";
  const d = new Date(isoString);
  const time = d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
  return `${MONTHS[d.getMonth()]} ${d.getDate()}, ${time}`;
};

const Row = ({ label, children }) => (
  <div>
    <p className="text-xs text-gray-400 mb-0.5">{label}</p>
    {children}
  </div>
);

const JobSummary = ({ jobData }) => {
  const badgeClass =
    STATUS_BADGE_COLOR[jobData.status] || "bg-gray-100 text-gray-700";

  return (
    <div className="bg-gray-50 rounded-xl p-4 flex flex-col gap-3">
      <p className="text-xs text-gray-500">Job summary</p>

      <Row label="Status">
        <span
          className={`inline-block text-xs px-2.5 py-0.5 rounded-full capitalize ${badgeClass}`}
        >
          {jobData.status}
        </span>
      </Row>

      <Row label="Locked">
        <p className="text-sm text-black">{jobData.locked ? "Yes" : "No"}</p>
      </Row>

      <Row label="Assigned to">
        <p className="text-sm text-black capitalize">
          {jobData.assignedTo || "Unassigned"}
        </p>
      </Row>

      <Row label="Network">
        <p className="text-sm text-black">{jobData.networkName || "—"}</p>
      </Row>

      <Row label="Scheduled">
        <p className="text-sm text-black">
          {formatScheduled(jobData.scheduledTime)}
        </p>
      </Row>

      <Row label="Dispatched Time">
        <p className="text-sm text-black">
          {formatScheduled(jobData.dispatchedAt)}
        </p>
      </Row>

      <div className="border-t border-gray-200 pt-3">
        <Row label="Pod Slip">
          {jobData.podSlipGenerated ? (
            <p className="text-sm text-black">
              Generated by{" "}
              <span className="font-medium">
                {jobData.podGeneratedBy || "—"}
              </span>
            </p>
          ) : (
            <p className="text-sm text-gray-400">Not generated yet</p>
          )}
        </Row>
      </div>
    </div>
  );
};

export default JobSummary;
