const STATUS_BADGE_COLOR = {
  Created: "bg-gray-100 text-gray-700",
  Assigned: "bg-blue-100 text-blue-700",
  PickedUp: "bg-purple-100 text-purple-700",
  AtOffice: "bg-indigo-100 text-indigo-700",
  Dispatched: "bg-green-100 text-green-700",
  Cancelled: "bg-red-100 text-red-700",
};

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const formatScheduled = (isoString) => {
  if (!isoString) return "—";
  const d = new Date(isoString);
  const time = d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
  return `${MONTHS[d.getMonth()]} ${d.getDate()}, ${time}`;
};

const Tile = ({ label, children }) => (
  <div className="rounded-lg bg-gray-50 border border-gray-100 px-3 py-2 min-w-0">
    <p className="text-[11px] font-medium uppercase tracking-wide text-gray-400 mb-0.5">
      {label}
    </p>
    <div className="text-sm text-black truncate">{children}</div>
  </div>
);

const JobSummary = ({ jobData }) => {
  const badgeClass =
    STATUS_BADGE_COLOR[jobData.status] || "bg-gray-100 text-gray-700";

  return (
    <div className="border border-gray-200 rounded-xl bg-white shadow-sm overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between gap-3 px-4 py-3 bg-gray-50 border-b border-gray-200">
        <div className="min-w-0">
          <h3 className="font-semibold text-black leading-tight">
            Job summary
          </h3>
          <p className="text-xs text-gray-500">Status and key details</p>
        </div>
        <span
          className={`text-xs font-medium px-2.5 py-1 rounded-full capitalize shrink-0 ${badgeClass}`}
        >
          {jobData.status}
        </span>
      </div>

      {/* Details */}
      <div className="p-4 grid grid-cols-2 gap-3">
        <Tile label="Assigned to">
          <span className="capitalize">
            {jobData.assignedTo || "Unassigned"}
          </span>
        </Tile>

        <Tile label="Locked">
          <span
            className={`inline-flex items-center gap-1.5 text-xs font-medium px-2 py-0.5 rounded-full ${
              jobData.locked
                ? "bg-black text-white"
                : "bg-gray-100 text-gray-600"
            }`}
          >
            <span
              className={`size-1.5 rounded-full ${
                jobData.locked ? "bg-white" : "bg-gray-400"
              }`}
            />
            {jobData.locked ? "Locked" : "Open"}
          </span>
        </Tile>

        <Tile label="Network">{jobData.networkName || "—"}</Tile>

        <Tile label="Scheduled">{formatScheduled(jobData.scheduledTime)}</Tile>

        <div className="col-span-2">
          <Tile label="Dispatched time">
            {formatScheduled(jobData.dispatchedAt)}
          </Tile>
        </div>
      </div>

      {/* Pod slip footer */}
      <div className="flex items-center gap-2 px-4 py-3 border-t border-gray-200 bg-gray-50 text-sm">
        <span
          className={`size-2 rounded-full shrink-0 ${
            jobData.podSlipGenerated ? "bg-green-500" : "bg-gray-300"
          }`}
        />
        {jobData.podSlipGenerated ? (
          <p className="text-gray-700 min-w-0 truncate">
            Pod slip generated by{" "}
            <span className="font-medium text-black">
              {jobData.podGeneratedBy || "—"}
            </span>
          </p>
        ) : (
          <p className="text-gray-400">Pod slip not generated yet</p>
        )}
      </div>
    </div>
  );
};

export default JobSummary;
