import { useState, useEffect, useRef, useCallback } from "react";
import toast from "react-hot-toast";
import api from "../api/axios";

const POLL_INTERVAL_MS = 3000;
const MAX_POLL_ATTEMPTS = 20; // ~1 minute ceiling before giving up

const SubmitSection = ({ jobData, jobId, setJobData }) => {
  const [submitting, setSubmitting] = useState(false);
  const [podSlipUrl, setPodSlipUrl] = useState(null);

  const pollTimerRef = useRef(null);
  const pollAttemptsRef = useRef(0);
  const pollRef = useRef(null);

  const refetchJob = async () => {
    const response = await api.get(`/api/partner/jobs/${jobId}`);
    setJobData(response.data.jobData);
  };

  const stopPolling = () => {
    if (pollTimerRef.current) {
      clearTimeout(pollTimerRef.current);
      pollTimerRef.current = null;
    }
    pollAttemptsRef.current = 0;
    setSubmitting(false);
  };

  const poll = useCallback(async () => {
    try {
      const response = await api.get(`/api/jobs/${jobId}/pod-slip`);
      const { podSlipStatus, podSlip } = response.data;

      if (podSlipStatus === "ready") {
        setPodSlipUrl(podSlip?.pdfUrl || null);
        toast.success("Pod slip ready");
        await refetchJob();
        stopPolling();
        return;
      }

      if (podSlipStatus === "unchanged") {
        setPodSlipUrl(podSlip?.pdfUrl || null);
        toast("No changes detected");
        stopPolling();
        return;
      }

      if (podSlipStatus === "failed") {
        setPodSlipUrl(podSlip?.pdfUrl || null); // fall back to last known-good file, if any
        toast.error("Pod slip generation failed — please try again");
        stopPolling();
        return;
      }

      // still "pending" — keep polling, up to a ceiling
      pollAttemptsRef.current += 1;
      if (pollAttemptsRef.current >= MAX_POLL_ATTEMPTS) {
        toast.error("Still generating — check back in a bit");
        stopPolling();
        return;
      }
      pollTimerRef.current = setTimeout(
        () => pollRef.current(),
        POLL_INTERVAL_MS,
      );
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed to check pod slip");
      stopPolling();
    }
  }, [jobId]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    pollRef.current = poll;
  }, [poll]);

  const handleSubmit = async () => {
    setSubmitting(true);
    setPodSlipUrl(null); // hide Download while a new attempt is in flight
    try {
      const response = await api.post(`/api/jobs/pickup/${jobId}/submit`);
      toast.success(response.data.message || "Pod slip generating");
      await refetchJob();
      pollAttemptsRef.current = 0;
      pollTimerRef.current = setTimeout(
        () => pollRef.current(),
        POLL_INTERVAL_MS,
      );
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed to submit job");
      setSubmitting(false);
    }
  };

  const handleDownloadPodSlip = async () => {
    try {
      const response = await fetch(podSlipUrl);
      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = "pod-slip.pdf";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      toast.error("Failed to download pod slip", err);
    }
  };

  // On mount: if a pod slip already exists, fetch its URL immediately —
  // no need to wait for a Check click to see something that's already there.
  useEffect(() => {
    if (!jobData.podSlipGenerated) return;

    const fetchExisting = async () => {
      try {
        const response = await api.get(`/api/jobs/${jobId}/pod-slip`);
        if (response.data.podSlip?.pdfUrl) {
          setPodSlipUrl(response.data.podSlip.pdfUrl);
        }
      } catch {
        // silent — if this fails, the user can still hit Generate/Submit
      }
    };
    fetchExisting();
  }, [jobId, jobData.podSlipGenerated]);

  // Clean up any in-flight poll timer if the component unmounts mid-poll
  useEffect(() => {
    return () => {
      if (pollTimerRef.current) clearTimeout(pollTimerRef.current);
    };
  }, []);

  return (
    <div className="border-t border-gray-200 pt-4">
      <h3 className="font-semibold text-black mb-2">Submission</h3>
      <p className="text-xs text-gray-500 mb-2">
        Requires weight and price to be saved first.
      </p>
      {jobData.podSlipGenerated && (
        <p className="text-xs text-gray-500 mb-2">
          Last generated by{" "}
          <span className="font-medium text-gray-700">
            {jobData.podGeneratedBy}
          </span>
        </p>
      )}

      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={handleSubmit}
          disabled={submitting}
          className="text-sm px-4 py-2 rounded-lg bg-black text-white hover:bg-gray-800 transition disabled:opacity-50 cursor-pointer"
        >
          {submitting ? "Generating..." : "Generate pod slip"}
        </button>

        {!submitting && podSlipUrl && (
          <button
            onClick={handleDownloadPodSlip}
            className="text-sm px-4 py-2 rounded-lg bg-gray-200 text-black hover:bg-gray-300 transition cursor-pointer"
          >
            Download pod slip
          </button>
        )}
      </div>
    </div>
  );
};

export default SubmitSection;
